<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('languages')->insert([
            [ 'name' => 'Afrikaans' ],
            [ 'name' => 'Amharic' ],
            [ 'name' => 'Arabic' ],
            [ 'name' => 'Assamese' ],
            [ 'name' => 'Azerbaijani' ],
            [ 'name' => 'Belarusian' ],
            [ 'name' => 'Bulgarian' ],
            [ 'name' => 'Bhojpuri' ],
            [ 'name' => 'Bengali' ],
            [ 'name' => 'Bosnian' ],
            [ 'name' => 'Catalan, Valencian' ],
            [ 'name' => 'Cebuano' ],
            [ 'name' => 'Czech' ],
            [ 'name' => 'Danish' ],
            [ 'name' => 'English' ],
            [ 'name' => 'Ewe' ],
            [ 'name' => 'German' ],
            [ 'name' => 'Greek, Modern' ],
            [ 'name' => 'Hindi' ],
            [ 'name' => 'Spanish' ],
            [ 'name' => 'Estonian' ],
            [ 'name' => 'Basque' ],
            [ 'name' => 'Persian' ],
            [ 'name' => 'Fula' ],
            [ 'name' => 'Finnish' ],
            [ 'name' => 'French' ],
            [ 'name' => 'Irish' ],
            [ 'name' => 'Galician' ],
            [ 'name' => 'Guarani' ],
            [ 'name' => 'Gujarati' ],
            [ 'name' => 'Hausa' ],
            [ 'name' => 'Haitian Creole' ],
            [ 'name' => 'Hebrew (modern)' ],
            [ 'name' => 'Chhattisgarhi' ],
            [ 'name' => 'Croatian' ],
            [ 'name' => 'Hungarian' ],
            [ 'name' => 'Armenian' ],
            [ 'name' => 'Indonesian' ],
            [ 'name' => 'Igbo' ],
            [ 'name' => 'Icelandic' ],
            [ 'name' => 'Italian' ],
            [ 'name' => 'Japanese' ],
            [ 'name' => 'Syro-Palestinian Sign Language' ],
            [ 'name' => 'Javanese' ],
            [ 'name' => 'Georgian' ],
            [ 'name' => 'Kikuyu' ],
            [ 'name' => 'Kyrgyz' ],
            [ 'name' => 'Kuanyama' ],
            [ 'name' => 'Kazakh' ],
            [ 'name' => 'Khmer' ],
            [ 'name' => 'Kannada' ],
            [ 'name' => 'Korean' ],
            [ 'name' => 'Krio' ],
            [ 'name' => 'Kashmiri' ],
            [ 'name' => 'Kurdish' ],
            [ 'name' => 'Latin' ],
            [ 'name' => 'Lithuanian' ],
            [ 'name' => 'Luxembourgish' ],
            [ 'name' => 'Latvian' ],
            [ 'name' => 'Magahi' ],
            [ 'name' => 'Maithili' ],
            [ 'name' => 'Malagasy' ],
            [ 'name' => 'Macedonian' ],
            [ 'name' => 'Malayalam' ],
            [ 'name' => 'Mongolian' ],
            [ 'name' => 'Marathi (Marāṭhī)' ],
            [ 'name' => 'Malay' ],
            [ 'name' => 'Maltese' ],
            [ 'name' => 'Burmese' ],
            [ 'name' => 'Nepali' ],
            [ 'name' => 'Dutch' ],
            [ 'name' => 'Norwegian' ],
            [ 'name' => 'Oromo' ],
            [ 'name' => 'Odia' ],
            [ 'name' => 'Oromo' ],
            [ 'name' => 'Panjabi, Punjabi' ],
            [ 'name' => 'Polish' ],
            [ 'name' => 'Pashto' ],
            [ 'name' => 'Portuguese' ],
            [ 'name' => 'Rundi' ],
            [ 'name' => 'Romanian, Moldavian, Moldovan' ],
            [ 'name' => 'Russian' ],
            [ 'name' => 'Kinyarwanda' ],
            [ 'name' => 'Sindhi' ],
            [ 'name' => 'Argentine Sign Language' ],
            [ 'name' => 'Brazilian Sign Language' ],
            [ 'name' => 'Chinese Sign Language' ],
            [ 'name' => 'Colombian Sign Language' ],
            [ 'name' => 'German Sign Language' ],
            [ 'name' => 'Algerian Sign Language' ],
            [ 'name' => 'Ecuadorian Sign Language' ],
            [ 'name' => 'Spanish Sign Language' ],
            [ 'name' => 'Ethiopian Sign Language' ],
            [ 'name' => 'French Sign Language' ],
            [ 'name' => 'British Sign Language' ],
            [ 'name' => 'Ghanaian Sign Language' ],
            [ 'name' => 'Irish Sign Language' ],
            [ 'name' => 'Indopakistani Sign Language' ],
            [ 'name' => 'Persian Sign Language' ],
            [ 'name' => 'Italian Sign Language' ],
            [ 'name' => 'Japanese Sign Language' ],
            [ 'name' => 'Kenyan Sign Language' ],
            [ 'name' => 'Korean Sign Language' ],
            [ 'name' => 'Moroccan Sign Language' ],
            [ 'name' => 'Mexican Sign Language' ],
            [ 'name' => 'Malaysian Sign Language' ],
            [ 'name' => 'Philippine Sign Language' ],
            [ 'name' => 'Polish Sign Language' ],
            [ 'name' => 'Portuguese Sign Language' ],
            [ 'name' => 'Russian Sign Language' ],
            [ 'name' => 'Saudi Arabian Sign Language' ],
            [ 'name' => 'El Salvadoran Sign Language' ],
            [ 'name' => 'Turkish Sign Language' ],
            [ 'name' => 'Tanzanian Sign Language' ],
            [ 'name' => 'Ukrainian Sign Language' ],
            [ 'name' => 'American Sign Language' ],
            [ 'name' => 'South African Sign Language' ],
            [ 'name' => 'Zimbabwe Sign Language' ],
            [ 'name' => 'Sinhala, Sinhalese' ],
            [ 'name' => 'Slovak' ],
            [ 'name' => 'Saraiki' ],
            [ 'name' => 'Slovene' ],
            [ 'name' => 'Shona' ],
            [ 'name' => 'Somali' ],
            [ 'name' => 'Albanian' ],
            [ 'name' => 'Serbian' ],
            [ 'name' => 'Swati' ],
            [ 'name' => 'Sunda' ],
            [ 'name' => 'Swedish' ],
            [ 'name' => 'Swahili' ],
            [ 'name' => 'Sylheti' ],
            [ 'name' => 'Tamil' ],
            [ 'name' => 'Telugu' ],
            [ 'name' => 'Tagalog' ],
            [ 'name' => 'Thai' ],
            [ 'name' => 'Tibetan' ],
            [ 'name' => 'Tigrinya' ],
            [ 'name' => 'Turkmen' ],
            [ 'name' => 'Tswana' ],
            [ 'name' => 'Turkish' ],
            [ 'name' => 'Urdu' ],
            [ 'name' => 'Uyghur' ],
            [ 'name' => 'Ukrainian' ],
            [ 'name' => 'Uzbek' ],
            [ 'name' => 'Vietnamese' ],
            [ 'name' => 'Xhosa' ],
            [ 'name' => 'Yiddish' ],
            [ 'name' => 'Yoruba' ],
            [ 'name' => 'Cantonese' ],
            [ 'name' => 'Chinese' ],
            [ 'name' => 'Zulu' ],
        ]);
    }
}
